config/routes.rb
Rubyplus::Application.routes.draw do

  resources :episodes do
    member do
      get 'download'
    end
  end

  namespace :admin do 
    resources :episodes, :testimonials
  end

  resources :testimonials
  
  match 'privacy' => 'episodes#privacy'
  
  root :to => 'episodes#index'
  
end

app/models/download.rb
class Download < ActiveRecord::Base
  belongs_to :episode
  
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  has_many :downloads
  
  acts_as_taggable_on :tags
  
  def self.recent(number)
    find(:all, :conditions => ['published_at <= ?', Time.now], :order => "sequence DESC", :limit => number)
  end
  
  def self.latest
    find(:all, :order => "sequence DESC", :limit => 5)
  end
  
  def self.get_all
    find(:all, :order => "sequence DESC" )
  end

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
end

app/controllers/admin/episodes_controller.rb
class Admin::EpisodesController < AdminController
  before_filter :authenticate
  
  def index
    @episodes = Episode.latest
  end

  def show
    @episode = Episode.find(params[:id])
  end

  def new
    @episode = Episode.new
  end

  def edit
    @episode = Episode.find(params[:id])
    @tags = @episode.tag_list
  end

  def create
    @episode = Episode.new(params[:episode])
    tag(params[:tags])

    if @episode.save
      flash[:notice] = 'Episode was successfully created.'
      redirect_to admin_episodes_url
    else
      render :action => "new" 
    end
  end

  def update
    @episode = Episode.find(params[:id])
    tag(params[:tags])

    if @episode.update_attributes(params[:episode])
      flash[:notice] = 'Episode was successfully updated.'
      redirect_to admin_episodes_url
    else
      render :action => "edit" 
    end
  end

  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy

    redirect_to admin_episodes_url
  end

  private

  def tag(key_words)
    @episode.tag_list = key_words
  end
end

app/controllers/admin/testimonials_controller.rb
class Admin::TestimonialsController < AdminController
  before_filter :authenticate

  def index
    @testimonials = Testimonial.all
  end

  def show
    @testimonial = Testimonial.find(params[:id])
  end

  def new
    @testimonial = Testimonial.new
  end

  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  def create
    @testimonial = Testimonial.new(params[:testimonial])

    if @testimonial.save
      flash[:notice] = 'Testimonial was successfully created.'
      redirect_to admin_testimonials_url
    else
      render :action => "new"
    end
  end

  def update
    @testimonial = Testimonial.find(params[:id])

    if @testimonial.update_attributes(params[:testimonial])
      flash[:notice] = 'Testimonial was successfully updated.'
      redirect_to admin_testimonials_url
    else
      format.html { render :action => "edit" }
    end
  end

  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy

    redirect_to admin_testimonials_url
  end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  helper :all # include all helpers, all the time

  # See ActionController::RequestForgeryProtection for details
  # Uncomment the :secret if you're not using the cookie session store
  protect_from_forgery # :secret => '76f7825fbbd6ecc648c24276bb6cc588'
  
  layout 'admin'
  uses_tiny_mce(:options => {:theme => 'advanced',
    :browsers => %w{msie gecko},
    :theme_advanced_toolbar_location => "top",
    :theme_advanced_toolbar_align => "left",
    :theme_advanced_resizing => true,
    :theme_advanced_resize_horizontal => false,
    :paste_auto_cleanup_on_paste => true,
    :theme_advanced_buttons1 => %w{bold italic underline strikethrough separator justifyleft justifycenter justifyright indent outdent separator bullist numlist forecolor backcolor separator link unlink image undo redo},
    :theme_advanced_buttons2 => [],
    :theme_advanced_buttons3 => [],
    :plugins => %w{contextmenu paste}},
    :only => [:new, :edit, :show, :index])
    
  protected
  
  def authenticate
    authenticate_or_request_with_http_basic do|user_name, password|
      user_name == ADMIN_CONFIG['username'] && password == ADMIN_CONFIG['password']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def index
    @page_title = "Ten Recent Episodes of Ruby and Rails Screencasts"
    @meta_description = "Ruby and Rails screencasts containing practical tips, tricks and tutorials for software developers."

    @episodes = Episode.all
  end

  def show
    @episode = Episode.find(params[:id])
    @page_title = "#{@episode.title}"
  end

  def destroy
    raise "You cannot destroy episodes"  
  end


  def download
    episode = Episode.find(params[:id])

    track_download(episode)                             
    redirect_to episode.download_link
  end

  def privacy
    render  :layout => false 
  end

  private

  def track_download(episode)
    episode.downloads.create(:episode_id => episode.id, :remote_ip => request.remote_ip)
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  def index
    @testimonials = Testimonial.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_published_at(episode)
    episode.published_at.strftime("%b %d, %Y")
  end
end

app/views/admin/episodes/_episode.html.erb
<div class="episode">
	<div class="side">
		<div class="number"><%= @episode.sequence %></div>
		<div class="published_at"><%= display_published_at(@episode) %> </div>
	</div>
	<div class="main">
		<h2><%= @episode.title %></h2>
		<div class="description">
			<%= raw(@episode.description) %>
		</div>
		<div class="download">
			<%= link_to "Download", @episode.download_link %>
			
			<span class="stats"> (<%= @episode.size %> MB, <%= @episode.duration %>)</span>
		</div>
		<div>
			Tags: <%= @episode.tag_list.join(", ") %>
		</div>
		
	  <%= link_to 'Show', admin_episode_path(@episode) %>
	  <%= link_to 'Edit', edit_admin_episode_path(@episode) %> 
	  <%= link_to 'Destroy', :controller=>"admin/episodes", :action=>"destroy" %>
	</div>
 
</div>

app/views/admin/episodes/_form.html.erb
<% form_for([:admin, @episode]) do |f| %>

<p>
   <b>Title</b><br />
   <%= f.text_field :title %>
 </p>

 <p>
   <b>Description</b><br />
   <%= f.text_area :description,  :class => "mceEditor" %>
 </p>

 <p>
   <b>Sequence</b><br />
   <%= f.text_field :sequence %>
 </p>

 <p>
    <b>Publish Date</b><br />
   <%= f.date_select :published_at %>
 </p>

 <p>
   <b>Download link</b><br />
   <%= f.text_field :download_link %>
 </p>

 <p>
   <b>Size</b><br />
   <%= f.text_field :size %>
 </p>

 <p>
   <b>Duration</b><br />
   <%= f.text_field :duration %>
 </p>

 <p>
   <b>Tags</b><br />
   <%= text_field_tag('tags', @tags) %>
 </p>

 <p>
   <%= f.submit button_tag %>
 </p>

<% end %>

app/views/admin/episodes/edit.html.erb
<fieldset>
<legend>Editing episode</legend>


<% if @episode.errors.any? %>
	<%= render :partical => "shared/error_messages", :target => @episode   %>
 <% end %>

<%= render :partial => "form", :locals => { :button_tag => "Update", :tags =>  @tags }  %>

<%= link_to 'Show', admin_episode_path(@episode) %> |
<%= link_to 'Back', admin_episodes_path %>

</fieldset>

app/views/admin/episodes/index.html.erb
<fieldset>
<legend></legend>

<% for episode in @episodes %>

<div class="episode">
	<div class="side">
		<div class="number"><%= episode.sequence %></div>
		<div class="published_at"><%= display_published_at(episode) %> </div>
	</div>
	<div class="main">
		<h2><%= episode.title %></h2>
		<div class="description">
			<%= raw(episode.description) %>
		</div>
		<div class="download">
			<span class="stats"> (<%= episode.size %> MB, <%= episode.duration %>)</span>
		</div>
		<div>
			Tags: <%= episode.tag_list.join(", ") %>
		</div>
	  <%= link_to 'Show', admin_episode_path(episode)  %>
	  <%= link_to 'Edit', edit_admin_episode_path(episode) %>
	</div>
 
</div>
<% end %>

<br />

<%= link_to 'New episode', new_admin_episode_path %>

</fieldset>

app/views/admin/episodes/new.html.erb
<fieldset>
<legend>New episode</legend>

<% if @episode.errors.any? %>
	<%= render :partical => "shared/error_messages", :target => @episode   %>
<% end %>

<%= render :partial => "form", :locals => { :button_tag => "Create"  }  %>

<%= link_to 'Back', admin_episodes_path %>

</fieldset>

app/views/admin/episodes/show.html.erb
<fieldset>
<legend> Episode</legend>

<% if @episode.errors.any? %>
	<%= render :partical => "shared/error_messages", :target => @article   %>
 <% end %>

 <%= render :partial => "episode"  %>

<%= link_to 'Back', admin_episodes_path %>

</fieldset>

app/views/admin/maintenance.html.erb
<html xmlns="http://www.w3.org/1999/xhtml" 
version="-//W3C//DTD XHTML 1.1//EN" xml:lang="en"> 
<head> 
<title>Custom Maintenance Page</title> 
<meta http-equiv="Content-type" content="text/html; charset=utf-8" /> 
<link href="/stylesheets/maintenance.css" rel="stylesheet" type="text/css" /> 
</head> 
<body> 
<div id="content"> 
<img src="http://railsrecipes.com/images/fr_arr.jpg" 
alt="Recipes" /> 
<h1> 
We're currently offline for <%= reason ? reason : "maintenance" %> 
as of <%= Time.now.strftime("%I:%M %p %Z") %>. 
</h1> 
<p> 
Sorry for the inconvenience. We'll be back 
<%= deadline ? "by #{deadline}" : "shortly" %>. 
Refer a job opening and make $1200 <a href="http://www.zepho.com/referral.html">Referral Bonus</a>.  
</p> 
</div> 
</body> 
</html> 

app/views/admin/testimonials/_form.html.erb
<p>
  <b>Title</b><br />
  <%= f.text_field :title %>
</p>

<p>
  <b>Body</b><br />
  <%= f.text_area :body %>
</p>

<p>
  <%= f.submit button_text %>
</p>

app/views/admin/testimonials/edit.html.erb
<fieldset>
<legend>Editing testimonial</legend>

<% if @testimonial.errors.any? %>
	<%= render :partical => "shared/error_messages", :target => @testimonial   %>
 <% end %>

<% form_for([:admin, @testimonial]) do |f| %>
<%= render :partial => "form", :locals => { :f => f, :button_text => "Update"  }  %>
<% end %>

</fieldset>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/admin/testimonials/index.html.erb
<fieldset>
<legend>Testimonials</legend>

<table>

<% for testimonial in @testimonials %>
  <tr>
    <th><%= testimonial.title %> </th>
  </tr>

  <tr>
    <td><%= raw(testimonial.body) %></td>
  </tr>
<% end %>
</table>

<br />

</fieldset>

<%= link_to "New Testimonial", new_admin_testimonial_url %>

app/views/admin/testimonials/new.html.erb
<fieldset>
<legend>New testimonial</legend>

<% if @testimonial.errors.any? %>
	<%= render :partical => "shared/error_messages", :target => @testimonial   %>
<% end %>



<% form_for([:admin, @testimonial]) do |f| %>
 <%= render :partial => "form", :locals => { :f => f, :button_text => "Create"  }  %>
<% end %>

</fieldset>

<%= link_to 'Back', admin_testimonials_path %>

app/views/admin/testimonials/show.html.erb
<fieldset>
<legend>Testimonial</legend>

<p>
  <b>Body:</b>
  <%= h @testimonial.body %>
</p>

</fieldset>

<%= link_to 'Edit', edit_admin_testimonial_path(@testimonial) %> |
<%= link_to 'Back', admin_testimonials_path %>

app/views/episodes/_episode.html.erb
<tr class="<%= cycle('odd', 'even') -%>" >
	<td><%= episode.sequence %></td>
	<td><%= link_to "#{episode.title}", episode %></td>
</tr>

app/views/episodes/index.html.erb
<fieldset>
<legend>Recent Episodes of Ruby and Rails Screencasts</legend>

<% for episode in @episodes %>

<div class="episode">
	<div class="side">
		<div class="number"><%= episode.sequence %></div>
		<div class="published_at"><%= display_published_at(episode) %> </div>
	</div>
	<div class="main">
		<h2><%= link_to episode.title, episode %></h2>
		<div class="description">
			<%= raw(episode.description) %>
		</div>
		<div class="download">
			<%= link_to "Download", download_episode_url(episode) %>
			<span class="stats"> (<%=h episode.size %> MB, <%=h episode.duration %>)</span>
		</div>
		
	</div>

</div>
<% end %>

Sponsored by <a href="http://www.creditcardslogic.com">Credit Cards</a> Logic 

</fieldset>

app/views/episodes/privacy.html.erb
<h3 align="center">Privacy Policy</h3>

There is nothing here</p>

<ol>

<li>
	Mary had a little lamb.
</li> 

<li>
	Little piggy went to the market
</li> 
</ol>

<p class="highlight">Learn to write and get rich quick<p>

<p>
Become a Ninja coder and take over world!
</p>

<p class="highlight"> You can relax now.</p>

<p align="right">
<a href="#" class="lbAction" rel="deactivate" >Close Window</a>	
</p>

app/views/episodes/show.html.erb
<% @page_title = @episode.title %>

<fieldset>
<legend> </legend>

<div class="episode">
	<div class="side">
		<div class="number"><%= @episode.sequence %></div>
		<div class="published_at"><%= display_published_at(@episode)%>   </div>	
	</div>
	<div class="main">
		<h2><%= @episode.title %></h2>
		<div class="description">
			<%= raw(@episode.description) %>
		</div>
		
		  <div class="download">
			<%= link_to "Download", download_episode_url(@episode) %>
			<span class="stats"> (<%= @episode.size %> MB, <%= @episode.duration %>)</span>
		  </div>
	</div>

</div>

</fieldset>

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-US">

<head>
  <title><%= @page_title || 'Ruby Plus - Free Ruby Screencasts' %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  
  <%= stylesheet_link_tag 'style' %>
  <%= stylesheet_link_tag 'main' %>
  <%= javascript_include_tag :defaults %>
	<%= include_tiny_mce_if_needed %>

</head>

  <body>

<!-- ##### Header ##### -->    
	<div id="header">
		<div class="superHeader">
  	  	    <span>Welcome Guest </span>
	  </div>
	  
      <div class="midHeader">
        <h1 class="headerTitle" lang="la">Ruby Plus</h1>
        <div class="headerSubTitle" title="Free Ruby Screencasts">
          Free Ruby Screencasts
        </div>
      </div>

	  <div class="subHeader">
		<span class="doNotDisplay">Navigation:</span>
		<%= link_to 'Episodes', admin_episodes_url %>
		| <%= link_to 'Testimonials', admin_testimonials_url   %>
	  </div>
	
    </div>
		
    <!-- ##### Main Copy ##### -->

    <div id="main-copy">
	
		
		<% flash.each do |key,value| %>
		<div id="flash" class="flash_<%= key %>" >
			<span class="message"><%= value %></span>
		</div>
		<% end -%>

		<%= yield :layout %>
		
	
    </div>


    <!-- ##### Footer ##### -->

    <div id="footer">
      <div class="doNotPrint">
	  
        
      </div>

      <div>
        Copyright &copy; 2007 - 2011, rubyplus.org
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-US">

<head>
  <title> <%= @page_title || "Free Ruby and Rails Screencasts"  %> </title>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

  <%= stylesheet_link_tag :all, :cache => true  %>
  <%= javascript_include_tag :all, :cache => true  %>
  <%= include_tiny_mce_if_needed %>

</head>

  <body>

<!-- ##### Header VER 0.39 ##### -->    
	<div id="header">
		<div class="superHeader" id="login">
		    <span>Welcome Guest</span>
	    </div>
	  
      <div class="midHeader">
        <h1 class="headerTitle" lang="la">Ruby Plus</h1>
        <div class="headerSubTitle" title="Free Ruby and Rails Screencasts">
          	<%= link_to 'Free Ruby and Rails Screencasts', episodes_url   %>
        </div>
      </div>

	  <div class="subHeader">
		<span class="doNotDisplay">Navigation:</span>
		<%= link_to 'Home', episodes_url   %> |
		<%= link_to 'Testimonials', testimonials_url %>
		
	  </div>
	
    </div>
		
	<div id="side-bar">

    	 <!-- ##### Left Sidebar ##### -->
		
	      <div class="leftSideBar">

			   <p class="sideBarTitle" align="center">Ruby Meetup</p>
			    <div class="box">
			      <span class="sideBarText" align="center">
				     If you live in the bay area, check out 
			         <%= link_to 'Silicon Valley Ruby Meetup', 'http://www.meetup.com/silicon-valley-ruby/' %>
			     </span>
			    </div>	
							
		  </div>
	
    <!-- ##### Right Sidebar ##### -->
	
		
	<div class="rightSideBar">
		
		 <p class="sideBarTitle"  align="center">Recommend Me</p>
		  <div class="badge" align="center"><a href="http://www.workingwithrails.com/recommendation/new/person/8567-bala-paranj"><img alt="Recommend Me" src="http://workingwithrails.com/images/tools/compact-small-button.jpg" /></a>
		 </div>
		
		<div>
			<p class="sideBarTitle"  align="center">Help Me</p>
			<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
			<input type="hidden" name="cmd" value="_s-xclick">
			<input type="hidden" name="hosted_button_id" value="3FJRL47Q42V9C">
			<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
			<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
			</form>
		</div>		
			 <p class="sideBarTitle"  align="center">Bookmark this Site</p>
			  <div class="badge" align="center">
				<script type="text/javascript">
				  addthis_url    = location.href;  
				  addthis_title  = document.title; 
				  addthis_pub    = 'bparanj';    
				</script><script type="text/javascript" src="http://s7.addthis.com/js/addthis_widget.php?v=12" ></script>
			 </div>
			
			 <p class="sideBarTitle"  align="center">Required</p>
			  <div class="badge" align="center"><a href="http://www.apple.com/quicktime/download/"><img src="/images/quicktime.gif" width="88" height="31" alt="Get Quicktime Player" /></a>
			 </div>
			
	</div>	
	
	
    <!-- ##### Main Copy ##### -->

    <div id="main-copy">
	
		
		<% flash.each do |key,value| %>
		<div id="flash" class="flash_<%= key %>" >
			<span class="message"><%= value %></span>
		</div>
		<% end -%>

		<%= yield :layout %>
		
			
		<div align="center">
      		<a href="http://www.workingwithrails.com/recommendation/new/person/8567-bala-paranj">
			   <img alt="Recommend Me" src="http://workingwithrails.com/images/tools/compact-med-button.jpg" />
			</a>
		</div>
    </div>


    <!-- ##### Footer ##### -->

    <div id="footer">
      <div class="doNotPrint">
	            <a href="/privacy" class="lbOn">Privacy Policy</a> 

        <!-- <a href="./index.html">Tell a Friend</a> |
                <a href="./index.html">Site Map</a> |
                <a href="./index.html">Feedback</a> |
                <a href="./index.html">Help</a> -->
      </div>

      <div>
        Copyright &copy; 2007 - 2011, rubyplus.org
      </div>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>  
<div id="errorExplanation">  
  <h2><%= pluralize(target.errors.count, "error") %> occurred:</h2>  
  <ul>  
  <% target.errors.full_messages.each do |msg| %>  
    <li><%= msg %></li>  
  <% end %>  
  </ul>  
</div>  
<% end %>

app/views/testimonials/index.html.erb
<fieldset>
<legend>Testimonials</legend>

<table>

<% for testimonial in @testimonials %>
  <tr>
    <th><%= testimonial.title %> </th>
  </tr>

  <tr>
    <td><%= raw(testimonial.body) %></td>
  </tr>
<% end %>
</table>

<br />

</fieldset>